# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcaseresult',
            name='updatePerson',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=50, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='subtestcaseresult',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last Update Date', verbose_name='Last Update Date'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='updateDate',
            field=models.DateField(default='2018-07-27', help_text='Last Update Date', verbose_name='Last Update Date'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='updatePerson',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=50, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='testsuiteresult',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='End Time', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='testsuiteresult',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Start Time', verbose_name='Start Time'),
        ),
    ]
