# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_suite', '0002_auto_20180728_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtestcaseresult',
            old_name='name',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='subtestcaseresult',
            old_name='suitID',
            new_name='test_suit',
        ),
    ]
