# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(help_text='Project Name', max_length=255, primary_key=True, serialize=False, verbose_name='Project Name')),
                ('key', models.CharField(blank=True, help_text='Project Abbreviations', max_length=255, null=True, verbose_name='Project Abbreviations')),
                ('projectLead', models.CharField(blank=True, help_text='Project Leader', max_length=50, null=True, verbose_name='Project Leader')),
                ('url', models.CharField(blank=True, help_text='Project URL', max_length=255, null=True, verbose_name='Project URL')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, help_text='Created Time', verbose_name='Created Time')),
            ],
            options={
                'verbose_name': 'ProjectName',
                'verbose_name_plural': 'ProjectName',
            },
        ),
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sprint Name', max_length=255, verbose_name='Sprint Name')),
                ('startDate', models.DateField(help_text='Start Date', verbose_name='Start Date')),
                ('endDate', models.DateField(help_text='End Date', verbose_name='End Date')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, help_text='Created Time', verbose_name='Created Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_manage.Projects', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'SprintName',
                'verbose_name_plural': 'SprintName',
            },
        ),
    ]
