# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtestcases',
            old_name='sub',
            new_name='caseID',
        ),
    ]
