# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='framework',
            field=models.CharField(choices=[('Selenium', 'Selenium'), ('Cucumber', 'Cucumber'), ('UFT', 'UFT')], max_length=20),
        ),
    ]
