# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='result',
            field=models.CharField(default='', help_text='Execution Result', max_length=50, verbose_name='Execution Result'),
        ),
        migrations.AlterField(
            model_name='subtestcases',
            name='storyId',
            field=models.CharField(blank=True, help_text='Story ID', max_length=255, null=True, verbose_name='Story ID'),
        ),
    ]
