# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0002_auto_20180722_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='result',
            field=models.CharField(blank=True, default='', help_text='Execution Result', max_length=50, null=True, verbose_name='Execution Result'),
        ),
    ]
