# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0002_auto_20180713_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Release Name', max_length=255, verbose_name='Release Name')),
                ('startDate', models.DateField(help_text='Start Date', verbose_name='Start Date')),
                ('endDate', models.DateField(help_text='End Date', verbose_name='End Date')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, help_text='Created Time', verbose_name='Created Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_manage.Projects', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'ReleaseName',
                'verbose_name_plural': 'ReleaseName',
            },
        ),
        migrations.AlterUniqueTogether(
            name='releases',
            unique_together=set([('project', 'name')]),
        ),
    ]
