# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0003_auto_20180722_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
    ]
