# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0003_auto_20180716_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.CharField(help_text='Sprint Name', max_length=255, verbose_name='Sprint Name')),
                ('release', models.CharField(help_text='Release Name', max_length=255, verbose_name='Release Name')),
                ('story_id', models.CharField(help_text='Story ID', max_length=255, verbose_name='Story ID')),
                ('summary', models.CharField(help_text='Story Summary', max_length=255, verbose_name='Story Summary')),
                ('assignee', models.CharField(help_text='Assignee', max_length=50, verbose_name='Assignee')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, help_text='Created Time', verbose_name='Created Time')),
                ('project', models.ForeignKey(help_text='Project Name', on_delete=django.db.models.deletion.CASCADE, to='projects_manage.Projects', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'StoryID',
                'verbose_name_plural': 'StoryID',
            },
        ),
        migrations.AlterField(
            model_name='releases',
            name='project',
            field=models.ForeignKey(help_text='Project Name', on_delete=django.db.models.deletion.CASCADE, to='projects_manage.Projects', verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='project',
            field=models.ForeignKey(help_text='Project Name', on_delete=django.db.models.deletion.CASCADE, to='projects_manage.Projects', verbose_name='Project Name'),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together=set([('project', 'story_id', 'sprint')]),
        ),
    ]
