# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0003_auto_20180724_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='description',
            field=models.CharField(blank=True, help_text='Test Case Description', max_length=500, null=True, verbose_name='Test Case Description'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='description',
            field=models.CharField(blank=True, help_text='Test Case Description', max_length=500, null=True, verbose_name='Test Case Description'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='updatePerson',
            field=models.CharField(default='', help_text='Last Update User', max_length=50, verbose_name='Last Update User'),
        ),
    ]
