# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0004_auto_20180724_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releases',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AlterField(
            model_name='releases',
            name='last_update_user',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=100, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AlterField(
            model_name='sprints',
            name='last_update_user',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=100, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_update_user',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=100, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='subtestcases',
            name='last_update_user',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=100, null=True, verbose_name='Last Update User'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='updateDate',
            field=models.DateField(default='2018-07-27', help_text='Last Update Date', verbose_name='Last Update Date'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='updatePerson',
            field=models.CharField(blank=True, default='', help_text='Last Update User', max_length=50, null=True, verbose_name='Last Update User'),
        ),
    ]
