# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0004_auto_20180718_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='releases',
            name='updated_time',
            field=models.DateTimeField(default=None, help_text='Updated Time', verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='sprints',
            name='updated_time',
            field=models.DateTimeField(default=None, help_text='Updated Time', verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_time',
            field=models.DateTimeField(default=None, help_text='Updated Time', verbose_name='Updated Time'),
        ),
    ]
