# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0005_auto_20180718_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releases',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='sprints',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='releases',
            name='last_update_time',
            field=models.DateTimeField(default=None, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AddField(
            model_name='releases',
            name='last_update_user',
            field=models.CharField(default=None, help_text='Last Update User', max_length=100, verbose_name='Last Update User'),
        ),
        migrations.AddField(
            model_name='sprints',
            name='last_update_time',
            field=models.DateTimeField(default=None, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AddField(
            model_name='sprints',
            name='last_update_user',
            field=models.CharField(default=None, help_text='Last Update User', max_length=100, verbose_name='Last Update User'),
        ),
        migrations.AddField(
            model_name='story',
            name='last_update_time',
            field=models.DateTimeField(default=None, help_text='Last Update Time', verbose_name='Last Update Time'),
        ),
        migrations.AddField(
            model_name='story',
            name='last_update_user',
            field=models.CharField(default=None, help_text='Last Update User', max_length=100, verbose_name='Last Update User'),
        ),
    ]
