# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manage', '0007_auto_20180718_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtestcases',
            name='application',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('API', 'API'), ('Siebel', 'Siebel'), ('C/S', 'Client/Server')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subtestcases',
            name='country',
            field=models.CharField(choices=[('US', 'US'), ('UK', 'UK'), ('DE', 'DE'), ('JP', 'JP'), ('IT', 'IT'), ('FR', 'FR'), ('CHN', 'CHN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subtestcases',
            name='framework',
            field=models.CharField(choices=[('SE', 'Selenium'), ('CU', 'Cucumber'), ('UFT', 'UFT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subtestcases',
            name='storyId',
            field=models.CharField(help_text='Story ID', max_length=255, verbose_name='Story ID'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='application',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('API', 'API'), ('Siebel', 'Siebel'), ('C/S', 'Client/Server')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='framework',
            field=models.CharField(choices=[('SE', 'Selenium'), ('CU', 'Cucumber'), ('UFT', 'UFT')], max_length=20),
        ),
    ]
