# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 01:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Created Time', verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, help_text='User Profile', max_length=500, null=True, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currentProject',
            field=models.CharField(blank=True, help_text='Current Project Name', max_length=100, null=True, verbose_name='Current Project Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, help_text='Email Address', max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Nick Name', max_length=30, null=True, verbose_name='Nick Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='Password', max_length=255, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(help_text='Login Name', max_length=255, unique=True, verbose_name='Login Name'),
        ),
    ]
