# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180706_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Updated Time', verbose_name='Updated Time'),
        ),
    ]
